# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\x12\x08\x62rokerpb\";\n\x0eProduceRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x11\n\x0fProduceResponse\"O\n\x0c\x46\x65tchRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x12\r\n\x05limit\x18\x04 \x01(\x05\"W\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0e\n\x06offset\x18\x04 \x01(\x03\x12\x11\n\tpartition\x18\x05 \x01(\x05\"4\n\rFetchResponse\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.brokerpb.Message\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x93\x02\n\rBrokerService\x12>\n\x07Produce\x12\x18.brokerpb.ProduceRequest\x1a\x19.brokerpb.ProduceResponse\x12\x38\n\x05\x46\x65tch\x12\x16.brokerpb.FetchRequest\x1a\x17.brokerpb.FetchResponse\x12<\n\tSubscribe\x12\x1a.brokerpb.SubscribeRequest\x1a\x11.brokerpb.Message0\x01\x12J\n\x0bHealthCheck\x12\x1c.brokerpb.HealthCheckRequest\x1a\x1d.brokerpb.HealthCheckResponseB+Z)bob-the-broker/internal/brokerpb;brokerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)bob-the-broker/internal/brokerpb;brokerpb'
  _globals['_PRODUCEREQUEST']._serialized_start=26
  _globals['_PRODUCEREQUEST']._serialized_end=85
  _globals['_PRODUCERESPONSE']._serialized_start=87
  _globals['_PRODUCERESPONSE']._serialized_end=104
  _globals['_FETCHREQUEST']._serialized_start=106
  _globals['_FETCHREQUEST']._serialized_end=185
  _globals['_MESSAGE']._serialized_start=187
  _globals['_MESSAGE']._serialized_end=274
  _globals['_FETCHRESPONSE']._serialized_start=276
  _globals['_FETCHRESPONSE']._serialized_end=328
  _globals['_SUBSCRIBEREQUEST']._serialized_start=330
  _globals['_SUBSCRIBEREQUEST']._serialized_end=363
  _globals['_HEALTHCHECKREQUEST']._serialized_start=365
  _globals['_HEALTHCHECKREQUEST']._serialized_end=385
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=387
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=424
  _globals['_BROKERSERVICE']._serialized_start=427
  _globals['_BROKERSERVICE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
